/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2015
 *
 * Name: NAMES of team members
 * Date: 30-Oct-2015
 * Time: 08:38:44
 *
 * Project: csci205_hw_01
 * Package: hw03.view
 * File: WaveViewer
 * Description:
 *
 * ****************************************
 */
package hw03.view;

import hw03.controller.WaveFormController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSlider;

/**
 *
 * @author tww014
 */
public class WaveViewer extends javax.swing.JFrame {
    private WaveFormComponent wfc;

    /**
     * Creates new form WaveViewer
     *
     * @param wfc The waveform component to use
     */
    public WaveViewer(WaveFormComponent wfc) {
        initComponents();
        initModel(wfc);
        this.wfc = wfc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel controlPanel = new javax.swing.JPanel();
        channelSelector = new javax.swing.JComboBox();
        playPauseButton = new javax.swing.JButton();
        zoomSlider = new javax.swing.JSlider();
        displayPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        channelSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        channelSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelSelectorActionPerformed(evt);
            }
        });
        controlPanel.add(channelSelector);

        playPauseButton.setText("Play");
        playPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPauseButtonActionPerformed(evt);
            }
        });
        controlPanel.add(playPauseButton);
        controlPanel.add(zoomSlider);

        getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(displayPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initModel(WaveFormComponent wfc) {
        displayPanel.setViewportView(wfc);
        channelSelector.setModel(wfc.getAudioModel().channelModel());
        zoomSlider.setModel(wfc.getAudioModel().getRangeModel());
        WaveFormController ctl = new WaveFormController(this,
                                                        wfc.getAudioModel());
        pack();
    }

    private void playPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPauseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playPauseButtonActionPerformed

    private void channelSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_channelSelectorActionPerformed

    /**
     * Get the channel selector
     *
     * @return The channel selector
     */
    public JComboBox getChannelSelector() {
        return channelSelector;
    }

    /**
     * Get the play/pause button
     *
     * @return The play/pause button
     */
    public JButton getPlayPauseButton() {
        return playPauseButton;
    }

    /**
     * Get the slider that controls the zoom level
     *
     * @return the slider that controls the zoom level
     */
    public JSlider getZoomSlider() {
        return zoomSlider;
    }

    /**
     * Update the view
     */
    public void refresh() {
        this.wfc.revalidate();
        this.wfc.repaint();
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox channelSelector;
    private javax.swing.JScrollPane displayPanel;
    private javax.swing.JButton playPauseButton;
    private javax.swing.JSlider zoomSlider;
    // End of variables declaration//GEN-END:variables
}
